/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosimulacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.text.DefaultCaret;
import org.jfree.chart.ChartPanel;
import proyectosimulacion.problemaBlackjack.Logic;
import proyectosimulacion.problemaDardos.SimulacionDardos;
import proyectosimulacion.problemaPuertas.SimulacionPuertas;

/**
 *
 * @author migueldiaz
 */
public class ProjectFrame extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ProjectFrame() {
        initComponents();


        DefaultCaret caret = (DefaultCaret) logSimulation1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        caret = (DefaultCaret) logSimulation2.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        caret = (DefaultCaret) logSimulation3.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        graphPanel1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        logSimulation1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        progressBar1 = new javax.swing.JProgressBar();
        noCambiarPuertaRButton = new javax.swing.JRadioButton();
        cambiarPuertaRButton = new javax.swing.JRadioButton();
        labelDelay1 = new javax.swing.JLabel();
        labelIter1 = new javax.swing.JLabel();
        iterationsSimulation1 = new javax.swing.JTextField();
        delaySimulation1 = new javax.swing.JTextField();
        beginSimulation1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        graphAverage2 = new javax.swing.JInternalFrame();
        graphProbability2 = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        logSimulation2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        progressBar2 = new javax.swing.JProgressBar();
        simulateButton2 = new javax.swing.JButton();
        jugadorMaloRB = new javax.swing.JRadioButton();
        jugadorBuenoRB = new javax.swing.JRadioButton();
        juegoAleatorioRB = new javax.swing.JRadioButton();
        labelDelay2 = new javax.swing.JLabel();
        labelIter2 = new javax.swing.JLabel();
        iterationsSimulation2 = new javax.swing.JTextField();
        delaySimulation2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        graphPanel31 = new javax.swing.JInternalFrame();
        graphPanel32 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        logSimulation3 = new javax.swing.JTextArea();
        graphPanel33 = new javax.swing.JInternalFrame();
        graphPanel34 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iterationsSimulation3 = new javax.swing.JTextField();
        dealerStrategy = new javax.swing.JRadioButton();
        personalStrategy = new javax.swing.JRadioButton();
        countingStrategy = new javax.swing.JRadioButton();
        simulateButton3 = new javax.swing.JButton();
        progressBar3 = new javax.swing.JProgressBar();
        labelDelay3 = new javax.swing.JLabel();
        delaySimulation3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 700));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1020, 720));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel2.setMaximumSize(new java.awt.Dimension(1024, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));

        graphPanel1.setVisible(true);

        logSimulation1.setColumns(20);
        logSimulation1.setRows(5);
        jScrollPane1.setViewportView(logSimulation1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        progressBar1.setStringPainted(true);

        buttonGroup1.add(noCambiarPuertaRButton);
        noCambiarPuertaRButton.setText("No Cambiar Puerta");

        buttonGroup1.add(cambiarPuertaRButton);
        cambiarPuertaRButton.setSelected(true);
        cambiarPuertaRButton.setText("Cambiar Puerta");

        labelDelay1.setText("Retardo (ms)");

        labelIter1.setText("Iteraciones");

        iterationsSimulation1.setText("0");
        iterationsSimulation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iterationsSimulation1KeyReleased(evt);
            }
        });

        delaySimulation1.setText("0");
        delaySimulation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delaySimulation1KeyReleased(evt);
            }
        });

        beginSimulation1.setText("Iniciar Simulación");
        beginSimulation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginSimulation1MouseClicked(evt);
            }
        });
        beginSimulation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginSimulation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarPuertaRButton)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(labelIter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(iterationsSimulation1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(labelDelay1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(delaySimulation1))
                            .addComponent(noCambiarPuertaRButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(beginSimulation1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelDelay1, labelIter1});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {delaySimulation1, iterationsSimulation1});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIter1)
                    .addComponent(iterationsSimulation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delaySimulation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDelay1))
                .addGap(18, 18, 18)
                .addComponent(cambiarPuertaRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noCambiarPuertaRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(beginSimulation1)
                .addGap(18, 18, 18)
                .addComponent(progressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelDelay1, labelIter1});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {delaySimulation1, iterationsSimulation1});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphPanel1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addComponent(graphPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulación 3 puertas", jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(1024, 700));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 600));

        graphAverage2.setVisible(true);

        graphProbability2.setAutoscrolls(true);
        graphProbability2.setMaximumSize(new java.awt.Dimension(408, 311));
        graphProbability2.setMinimumSize(new java.awt.Dimension(408, 311));
        graphProbability2.setVisible(true);

        logSimulation2.setColumns(20);
        logSimulation2.setRows(5);
        jScrollPane3.setViewportView(logSimulation2);

        progressBar2.setStringPainted(true);

        simulateButton2.setText("Iniciar Simulación");
        simulateButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulateButton2MouseClicked(evt);
            }
        });

        buttonGroup2.add(jugadorMaloRB);
        jugadorMaloRB.setText("Jugador Malo");

        buttonGroup2.add(jugadorBuenoRB);
        jugadorBuenoRB.setText("Jugador Bueno");

        buttonGroup2.add(juegoAleatorioRB);
        juegoAleatorioRB.setSelected(true);
        juegoAleatorioRB.setText("Juego Aleatorio");

        labelDelay2.setText("Retardo (ms)");

        labelIter2.setText("Iteraciones");

        iterationsSimulation2.setText("0");
        iterationsSimulation2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iterationsSimulation2KeyReleased(evt);
            }
        });

        delaySimulation2.setText("0");
        delaySimulation2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delaySimulation2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jugadorBuenoRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simulateButton2)
                                .addGap(82, 82, 82))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(juegoAleatorioRB)
                                    .addComponent(jugadorMaloRB)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(labelIter2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(iterationsSimulation2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(labelDelay2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(delaySimulation2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterationsSimulation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIter2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delaySimulation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDelay2))
                .addGap(18, 18, 18)
                .addComponent(juegoAleatorioRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorBuenoRB)
                    .addComponent(simulateButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugadorMaloRB)
                .addGap(18, 18, 18)
                .addComponent(progressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(graphProbability2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(graphAverage2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {graphAverage2, graphProbability2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphAverage2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graphProbability2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(414, 414, 414))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {graphAverage2, graphProbability2});

        try {
            graphProbability2.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTabbedPane1.addTab("Simulación Tiro al Blanco", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        graphPanel31.setMaximumSize(new java.awt.Dimension(35, 32));
        graphPanel31.setVisible(true);
        graphPanel31.getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        jPanel4.add(graphPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 403, 270));

        graphPanel32.setVisible(true);
        jPanel4.add(graphPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 431, 270));

        logSimulation3.setColumns(20);
        logSimulation3.setRows(5);
        jScrollPane2.setViewportView(logSimulation3);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 360, 260));

        graphPanel33.setVisible(true);
        jPanel4.add(graphPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 370, 270));

        graphPanel34.setVisible(true);
        jPanel4.add(graphPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 430, 260));

        jLabel1.setText("Iteraciones: ");

        iterationsSimulation3.setText("0");
        iterationsSimulation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterationsSimulation3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(dealerStrategy);
        dealerStrategy.setText("Estrategia Dealer");
        dealerStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerStrategyActionPerformed(evt);
            }
        });

        buttonGroup3.add(personalStrategy);
        personalStrategy.setText("Estrategia Personal");
        personalStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalStrategyActionPerformed(evt);
            }
        });

        buttonGroup3.add(countingStrategy);
        countingStrategy.setText("Estrategia Conteo");

        simulateButton3.setText("Iniciar Simulación");
        simulateButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulateButton3MouseClicked(evt);
            }
        });

        progressBar3.setStringPainted(true);

        labelDelay3.setText("Retardo (ms)");

        delaySimulation3.setText("0");
        delaySimulation3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delaySimulation3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDelay3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iterationsSimulation3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(delaySimulation3)))
                            .addComponent(progressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(simulateButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personalStrategy)
                            .addComponent(countingStrategy)
                            .addComponent(dealerStrategy))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(iterationsSimulation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelay3)
                    .addComponent(delaySimulation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dealerStrategy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(personalStrategy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countingStrategy)
                .addGap(18, 18, 18)
                .addComponent(simulateButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 282, 400, -1));

        jTabbedPane1.addTab("Simulación BlackJack", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beginSimulation1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginSimulation1MouseClicked
        final SimulacionPuertas p;
        if (cambiarPuertaRButton.isSelected()) {
            p = new SimulacionPuertas(this, 0);
        } else {
            p = new SimulacionPuertas(this, 1);
        }





        Thread worker = new Thread() {
            public void run() {
                try {
                    p.run();
                } catch (Exception ex) {
                }
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setProgressBar1(0);

                        JOptionPane.showMessageDialog(null, "Simulación del problema de las tres puertas ha sido completada", "Info", JOptionPane.INFORMATION_MESSAGE);

                    }
                });
            }
        };
        worker.start();
    }//GEN-LAST:event_beginSimulation1MouseClicked

    private void iterationsSimulation1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iterationsSimulation1KeyReleased
        try {
            Integer.parseInt(iterationsSimulation1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe inserar valores numéricos unicamente", "Atención!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_iterationsSimulation1KeyReleased

    private void delaySimulation1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delaySimulation1KeyReleased
        try {
            Integer.parseInt(delaySimulation1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe inserar valores numéricos unicamente", "Atención!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delaySimulation1KeyReleased

    private void iterationsSimulation2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iterationsSimulation2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_iterationsSimulation2KeyReleased

    private void delaySimulation2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delaySimulation2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_delaySimulation2KeyReleased

    private void simulateButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulateButton2MouseClicked
        final SimulacionDardos d;
        if (juegoAleatorioRB.isSelected()) {
            d = new SimulacionDardos(this, 0);
        } else if (jugadorBuenoRB.isSelected()) {
            d = new SimulacionDardos(this, 1);
        } else {
            d = new SimulacionDardos(this, 2);
        }





        Thread worker = new Thread() {
            public void run() {
                try {
                    d.run();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setProgressBar2(0);

                        JOptionPane.showMessageDialog(null, "Simulación del problema de los dardos ha finalizado", "Info", JOptionPane.INFORMATION_MESSAGE);

                    }
                });
            }
        };
        worker.start();



    }//GEN-LAST:event_simulateButton2MouseClicked

    private void dealerStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerStrategyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealerStrategyActionPerformed

    private void personalStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalStrategyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalStrategyActionPerformed

    private void beginSimulation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginSimulation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginSimulation1ActionPerformed

    private void iterationsSimulation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterationsSimulation3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iterationsSimulation3ActionPerformed

    private void simulateButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulateButton3MouseClicked
        final Logic logic;
        if (dealerStrategy.isSelected()) {
            logic = new Logic(this, 0,0);
        } else if (personalStrategy.isSelected()) {
            logic = new Logic(this, 1,0);
        } else {
            logic = new Logic(this, 2,1);
        }


        Thread worker = new Thread() {
            public void run() {
                try {
                    logic.run();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setProgressBar3(0);

                        JOptionPane.showMessageDialog(null, "Simulación del problema de BlackJack finalizada", "Info", JOptionPane.INFORMATION_MESSAGE);

                    }
                });
            }
        };
        worker.start();
    }//GEN-LAST:event_simulateButton3MouseClicked

    private void delaySimulation3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delaySimulation3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_delaySimulation3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ProjectFrame().setVisible(true);
            }
        });
    }

    public JTextField getDelaySimulation1() {
        return delaySimulation1;
    }

    public JTextField getIterationsSimulation1() {
        return iterationsSimulation1;
    }

    public void setLogSimulation1(String str) {
        this.logSimulation1.setText(str);
    }

    public void setGraphPanel1(ChartPanel chartPanel) {
        this.graphPanel1.setContentPane(chartPanel);
    }

    public void setGraphPanel31(ChartPanel chartPanel) {
        this.graphPanel31.setContentPane(chartPanel);
    }

    public void setGraphPanel32(ChartPanel chartPanel) {
        this.graphPanel32.setContentPane(chartPanel);
    }

    public void setGraphPanel33(ChartPanel chartPanel) {
        this.graphPanel33.setContentPane(chartPanel);
    }

    public void setGraphPanel34(ChartPanel chartPanel) {
        this.graphPanel34.setContentPane(chartPanel);
    }

    public void setProgressBar1(int porcentaje) {
        this.progressBar1.setValue(porcentaje);

    }

    public void setProgressBar2(int porcentaje) {
        this.progressBar2.setValue(porcentaje);

    }

    public void setProgressBar3(int porcentaje) {
        this.progressBar3.setValue(porcentaje);

    }

    public void setGraphProbability2(ChartPanel chartPanel) {
        this.graphProbability2.setContentPane(chartPanel);
    }

    public void setGrahpAverage2(ChartPanel chartPanel) {
        this.graphAverage2.setContentPane(chartPanel);
    }

    public JTextField getDelaySimulation2() {
        return delaySimulation2;
    }

    public JTextField getIterationsSimulation2() {
        return iterationsSimulation2;
    }

    public JTextField getIterationsSimulation3() {
        return iterationsSimulation3;
    }

    public void setLogSimulation2(String str) {
        this.logSimulation2.setText(str);
    }

    public void setLogSimulation3(String str) {
        this.logSimulation3.setText(str);
    }

    public JTextField getDelaySimulation3() {
        return delaySimulation3;
    }

    public void setDelaySimulation3(JTextField delaySimulation3) {
        this.delaySimulation3 = delaySimulation3;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginSimulation1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cambiarPuertaRButton;
    private javax.swing.JRadioButton countingStrategy;
    private javax.swing.JRadioButton dealerStrategy;
    private javax.swing.JTextField delaySimulation1;
    private javax.swing.JTextField delaySimulation2;
    private javax.swing.JTextField delaySimulation3;
    private javax.swing.JInternalFrame graphAverage2;
    private javax.swing.JInternalFrame graphPanel1;
    private javax.swing.JInternalFrame graphPanel31;
    private javax.swing.JInternalFrame graphPanel32;
    private javax.swing.JInternalFrame graphPanel33;
    private javax.swing.JInternalFrame graphPanel34;
    private javax.swing.JInternalFrame graphProbability2;
    private javax.swing.JTextField iterationsSimulation1;
    private javax.swing.JTextField iterationsSimulation2;
    private javax.swing.JTextField iterationsSimulation3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton juegoAleatorioRB;
    private javax.swing.JRadioButton jugadorBuenoRB;
    private javax.swing.JRadioButton jugadorMaloRB;
    private javax.swing.JLabel labelDelay1;
    private javax.swing.JLabel labelDelay2;
    private javax.swing.JLabel labelDelay3;
    private javax.swing.JLabel labelIter1;
    private javax.swing.JLabel labelIter2;
    private javax.swing.JTextArea logSimulation1;
    private javax.swing.JTextArea logSimulation2;
    private javax.swing.JTextArea logSimulation3;
    private javax.swing.JRadioButton noCambiarPuertaRButton;
    private javax.swing.JRadioButton personalStrategy;
    private javax.swing.JProgressBar progressBar1;
    private javax.swing.JProgressBar progressBar2;
    private javax.swing.JProgressBar progressBar3;
    private javax.swing.JButton simulateButton2;
    private javax.swing.JButton simulateButton3;
    // End of variables declaration//GEN-END:variables
}
